{
	"version": 1484490089,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/player-sheet0.png",
		"images/tilemap.png",
		"images/arrow-sheet0.png",
		"images/rock-sheet0.png",
		"images/playerphysics-sheet0.png",
		"images/rockbase-sheet0.png",
		"images/arrawcount.png",
		"images/board-sheet0.png",
		"images/bat-sheet0.png",
		"images/centopeia-sheet0.png",
		"images/centopeia-sheet1.png",
		"images/tucandeira-sheet0.png",
		"images/level.png",
		"images/sprite-sheet0.png",
		"images/feather-sheet0.png",
		"images/tiledbackground.png",
		"images/feathercount.png",
		"images/crystal-sheet0.png",
		"images/checkpoint-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/spritefont.png",
		"media/atirando.m4a",
		"media/atirando.ogg",
		"media/bossdano.m4a",
		"media/bossdano.ogg",
		"media/bossmorte.m4a",
		"media/bossmorte.ogg",
		"media/coletandocristal.m4a",
		"media/coletandocristal.ogg",
		"media/empurrandoblocos.m4a",
		"media/empurrandoblocos.ogg",
		"media/menunavegando.m4a",
		"media/menunavegando.ogg",
		"media/menuselecionando.m4a",
		"media/menuselecionando.ogg",
		"media/passos.m4a",
		"media/passos.ogg",
		"media/pegandovidas.m4a",
		"media/pegandovidas.ogg",
		"media/playerdano.m4a",
		"media/playerdano.ogg",
		"media/pulo.m4a",
		"media/pulo.ogg",
		"media/puloaterrisagem.m4a",
		"media/puloaterrisagem.ogg",
		"media/semflechas.m4a",
		"media/semflechas.ogg",
		"media/battlethemea - cynicmusic (boss).m4a",
		"media/battlethemea - cynicmusic (boss).ogg",
		"media/inarticulate - axton crolley (fase 2).m4a",
		"media/inarticulate - axton crolley (fase 2).ogg",
		"media/radakan - janne hanhisuanto (menu).m4a",
		"media/radakan - janne hanhisuanto (menu).ogg",
		"media/woods - axton crolley (fase 1).m4a",
		"media/woods - axton crolley (fase 1).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}